sudo: false

# let Gradle to use plain console output.
# see http://stackoverflow.com/questions/17942819/how-can-i-get-clean-gradle-output-on-travis-ci
env: TERM=dumb

language: android

jdk: oraclejdk7

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-23

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

before_install: cd code

script:
    # see http://tools.android.com/tech-docs/new-build-system/tips#TOC-Improving-Build-Server-performance.
    - ./gradlew build -PdisablePreDex

# Caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
